### PR TITLE
Add support for Carthage

### PR DESCRIPTION
**Pull request by mikaelpoq**
Currently Emarsys SDK doesn't support Carthage.

Carthage is another popular alternative to CocoaPods.

This PR makes some small changes to add support for Carthage:
- Add a new scheme in the Xcode project to compile `EmarsysSDK.framework`
- Create `EmarsysSDK/EmarsysSDK.h` with the list of public headers
- Mark these headers as public in the Xcode project

Following these changes, users will be able to use Emarsys SDK in their projects like this:
- Create a `Cartfile` containing `github "emartech/ios-emarsys-sdk" "master"`
- Run `carthage update`

These changes shouldn't affect CocoaPods and CI, but don't hesitate to ask if you have more questions.

### CODE REVIEW

**Comment by szabist** [comment]
Hi Mikael,

Thanks for this contribution, we really appreciate your efforts on improving the SDK.
We will review and test this PR soon.

**Comment by joshuapoq** [comment]
Hey @szabist! Please let us know how you'd like to proceed with this PR? I'm happy to rebase it or close it although it would be great if we could consume your SDK via Carthage!

Keep up the great work! 👍

**Comment by szabist** [comment]
Hello @joshuapoq 

Apologise for taking so long time to handle this PR, we plan to integrate this PR and add Carthage support. The delay on our side is because we want to make sure that we not just merge this PR but add the required steps to use Carthage and test with it to our build pipeline because we want to make sure that if we say Carthage is supported it stays so with our subsequent releases and we have means in place to detect if any of our future developments would break this support and we just could not find the time to do this yet.

Thanks for your work, we really appreciate that you help improve the SDK.

Best regards,
Istvan

**Comment by joshuapoq** [comment]
To keep you guys in the loop; I have updated but not yet fully tested the work in this PR on another branch. Please feel free to close this PR.

We are keeping our eyes on SwiftPM and I expect we'll move to it in the next month or so when the next Xcode version is released allowing for resources.

**Comment by szabist** [comment]
Hi @joshuapoq 

Thanks for keeping us informed about your plans, please let us know about your experience with Swift Package Manager, we added support for it in 2.4.0 of the Emarsys SDK and any feedback would be much appreciated.

Best regards,
Istvan

**Comment by joshuapoq** [comment]
Hi @szabist we will be adopting SwiftPM with the release of Xcode 12! 🙌 

Please close this PR as I do not have access and will no longer maintain the branch or fork once Xcode 12 is released.
It'll be great to finally drop the clunkiness of Carthage.

**Pull request closed without merging**
